- name: "APT - Add Docker GPG key"
  become: yes  
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  
- name: "APT - Add Docker repository"
  become: yes  
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    #repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    state: present
    filename: docker
  
- name: "APT - install misc packages"
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - "aptitude"
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
  
- name: "APT - install 'docker-ce'"
  become: yes
  apt:
    name: "docker-ce"
    update_cache: yes

