- name: clone oh-my-zsh for users
  become: yes
  become_user: '{{ username }}'
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
  args:
    chdir: '~{{ username }}'
    creates: '~{{ username }}/.oh-my-zsh'
 
- name: set default shell for users
  become: yes
  user:
    name: '{{ username }}'
    shell: /bin/zsh

- name: write .zshrc 
  become: yes
  become_user: '{{ username }}'
  template:
    src: zshrc.j2
    dest: '~{{ username }}/.zshrc'
    backup: yes
    mode: 'u=rw,go=r'
